#!/usr/bin/env bash
#
# Run all etcd tests
# ./test
# ./test -v
#
# Run tests for one package
#
# PKG=./funemain ./test
# PKG=funeagent ./test
set -e

# Invoke ./cover for HTML output
COVER=${COVER:-"-cover"}

source ./build

# Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
TESTABLE_AND_FORMATTABLE="funemain funeagent version actions emitter listener pkg/flags"
FORMATTABLE="$TESTABLE_AND_FORMATTABLE *.go integration"

# user has not provided PKG override
if [ -z "$PKG" ]; then
	TEST=$TESTABLE_AND_FORMATTABLE
	FMT=$FORMATTABLE

# user has provided PKG override
else
	# strip out leading dotslashes and trailing slashes from PKG=./foo/
	TEST=${PKG/#./}
	TEST=${TEST/#\//}
	TEST=${TEST/%\//}

	# only run gofmt on packages provided by user
	FMT="$TEST"
fi

# split TEST into an array and prepend REPO_PATH to each local package
split=(${TEST// / })
TEST=${split[@]/#/${REPO_PATH}/}

echo "Running tests..."

MACHINE_TYPE=$(uname -m)
if [ $MACHINE_TYPE != "armv7l" ]; then
  RACE="--race"
fi

go test -timeout 3m ${COVER} $@ ${TEST} ${RACE} -cpu 1,2,4

if [ -n "$INTEGRATION" ]; then
	echo "Running integration tests..."
	go test -timeout 10m $@ ${REPO_PATH}/integration -v -cpu 1,2,4
fi

echo "Checking gofmt..."
fmtRes=$(gofmt -l ${FMT})
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet ./...)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

if command -v go-nyet >/dev/null 2>&1; then
  echo "Checking go-nyet..."
  nyetRes=$(go-nyet -exitWith 0 ./...)
  if [ -n "${nyetRes}" ]; then
          echo -e "go-nyet checking failed:\n${nyetRes}"
          exit 255
  fi
fi

echo "Success"
